### ISSUE TITLE
Sliver in beacon style can't execute command

### ISSUE THREAD

**Issue by wxi3** [MythicAgents/sliver#6]
In the command Line ,it is normal
<img width="1508" alt="图片" src="https://github.com/user-attachments/assets/f882f001-e272-4b1d-a1e4-7834f4f0dd8d">
but in mythic ,it can not work
<img width="1428" alt="图片" src="https://github.com/user-attachments/assets/bdee214c-d23c-4066-8221-8237d4805dcb">

**Comment by spenceradolph** [comment]
@wxi3 Are you able to give more information about the setup to reproduce this bug? What versions of Sliver/Mythic are being used? What type of implant was created and what type of host is it running on?

**Comment by wxi3** [comment]
This is my version:
<img width="551" alt="image" src="https://github.com/user-attachments/assets/d96054bf-4bbf-436e-a9d0-ed288d383cd7">
my mean,when i user sliver to generate a beacon style implant,i can execute command in sliver command line ,but i can't work in mythic when i use this command : use （id）

**Comment by spenceradolph** [comment]
Your screenshot shows commands being run in the “shell” context, which isn’t normally allowed for beaconing implants.

**Comment by spenceradolph** [comment]
![Screenshot_2024-12-01_15-14-30](https://github.com/user-attachments/assets/1ddb4a9e-fe9f-4de0-b6c1-29bcd323245c)
I installed a fresh kali, fresh sliver, fresh mythic, and was able to successful build a local http beaconer and task it. Let me know if it's failing for other tasks, or perhaps there is something more specific about your setup that can be shared to further replicate the issue. Again, 'shell' is only applicable for 'session' type implants, not beacons.

Furthermore, I saw that the beaconer wasn't automatically added like sessions would be, but that could likely be easily added by adding more events into this area of the code like I have for auto-adding sessions.
https://github.com/MythicAgents/sliver/blob/8675e0be9ad21e86772bf1e968b71da03006407b/Payload_Type/sliverapi/sliverapi/SliverRequests/SliverAPI.py#L67

**Comment by wxi3** [comment]
Yes,you are right,Beacon can also run normally,my mistake.And i have some other question want to consult,as follows:
1. How to use Mythic to generate implants? and what is sliverconfig_file_uuid?
When i try to generate ,i don't know what is sliverconfig_file_uuid?,so i get this error:
<img width="977" alt="图片" src="https://github.com/user-attachments/assets/d5b79db7-b5d4-45e4-abe7-a412137b0384">
2.When i in mythic use sliverapi generate function to generate a implants,it failed：
i waited more than ten minutes,but still haven't generated it.
<img width="1048" alt="图片" src="https://github.com/user-attachments/assets/d0f08ef4-7e87-4149-9f16-38ae97b2aab8">
<img width="1414" alt="图片" src="https://github.com/user-attachments/assets/988812e3-cc04-4171-9cf3-1bc15d2d76ff">

3.The last,beacon or session can't exit in mythic,only is hide allowed

<img width="626" alt="图片" src="https://github.com/user-attachments/assets/479e1f8d-c4a7-4d6c-a01d-d049e3fbb3c1">

**Comment by spenceradolph** [comment]
1) sliverconfig_file_uuid is likely the uuid of the file you upload when connecting to sliver when creating the sliverapi callback. This can be found in Mythic in the files tab I believe. The reason this is needed, is potentially multiple sliver servers could exist, and I hadn't implemented an easy way to pick which one, and didn't want to assume only one was used, since Mythic supports multiple operations at the same time. In the future, perhaps this can be a dynamic drop down, but ideally you might just generate via the command line with the generate command, or with sliver directly instead of Mythic. I would need to test more to ensure that gui build functionality is working at 100%, it may be still buggy.

You might also notice that most of the generate options are not even available in that Mythic view, only because I did the bare minimum for that part of the proof of concept. All the other options could easily be added if this is the preferred method of building.

2) I think those implants are still 'generated', but just not uploaded into Mythic as well. That functionality wouldn't be too bad to handle, just api call to sliver to download after generating, then api call to Mythic to upload. That implant still exists on the Sliver server if you want to manually upload it in the meantime. Again, initial proof of concepts, but doable. 

3) I'd have to look into adding it, but this would also be doable. 
Here is actually the line in the sliver-py library I was using that could accomplish it. (referencing 1.6 sliver-py, but it's likely in the 1.5 version as well)
https://github.com/moloch--/sliver-py/blob/c9ca1dea1f92f6836eace21cf2f1592c36e5499c/src/sliver/client.py#L248

All in all, reasonable questions / bugs / things to implement. My motivation to work on it has stalled until Sliver officially releases version 1.6, since that simplifies some code.

**Comment by wxi3** [comment]
Thank for you response.
Is this the uuid you are referring to:
<img width="880" alt="图片" src="https://github.com/user-attachments/assets/777bd60b-c4e1-42fc-ac9a-3eb622db17da">
<img width="1061" alt="图片" src="https://github.com/user-attachments/assets/3efa92d0-8f15-401f-ae6a-887e586ce84a">

But it still failed ,and here is the error message
<img width="1215" alt="图片" src="https://github.com/user-attachments/assets/a83433c8-9af7-464f-93fa-816157e27f80">
`Build Message:

Sending Build command

StdErr: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mythic_container/agent_utils.py", line 70, in buildWrapper
    build_resp = await agent_builder.build()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Mythic/sliverimplant/agent_functions/builder.py", line 54, in build
    config = SliverClientConfig.parse_config(filecontent.Content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sliver/config.py", line 86, in parse_config
    return cls(**json.loads(data))
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0)
StdOut: 
`
Yes,i also noticed  that Mythic-Sliver still has many features that need improvement. It is a great tool.Thank for your reply,and i wish you a wonderful life.

**Comment by spenceradolph** [comment]
I don’t think that’s it, I think it’s located in the “files” and the one you selected is the pseudo implant that is created for sliverapi, which is 0 bytes.

If you have a fresh install, and create the sliverapi, you’d see which file it was in the files tab I believe.

**Comment by wxi3** [comment]
Is it this one?
<img width="1498" alt="图片" src="https://github.com/user-attachments/assets/babda33a-407d-4acb-8d79-6dfe467bf0d0">

**Comment by spenceradolph** [comment]
No, see if there’s an area to view files in the navbar in mythic, and find a file that corresponds to that sliver .cfg
